[workspace]
resolver = "2"
members = [
  "execution-handler",
  "ws-meta-executor"
]

[workspace.dependencies]
warp            = "0.3"
tokio           = { version = "1", features = ["full"] }
serde           = { version = "1.0", features = ["derive"] }
serde_json      = "1.0"
deadpool-postgres = "0.9"
tokio-postgres = "0.7.10"
sha2            = "0.10"
anyhow = "1.0.98"
hex = "0.4.3"
toml = "0.8.21"
bincode = "1.0"
base64 = "0.22.1"
reqwest = { version = "0.12.2", features = ["json"] }
async-trait = "0.1.88"
tracing = "0.1.41"
tracing-subscriber = "0.3.20"
stellar-strkey = "0.0.7"
md5 = "0.7.0"

#retroshade = { path = "../retroshade/retroshade" }
retroshade = { git = "https://github.com/xycloo/retroshade", rev="fb5f977" }

#rs-zephyr-common = {path="../rs-zephyr-sdk/zephyr-common"}
rs-zephyr-common = {git="https://github.com/xycloo/rs-zephyr-toolkit", branch="stellar-main-2"}

#zephyr = { package = "zephyr-vm", path = "../zephyr/rs-zephyr-env/" }
zephyr = { package = "zephyr-vm", git = "https://github.com/xycloo/zephyr", branch="actor" }

[workspace.dependencies.stellar-xdr]
version = "=23.0.0"
features = ["next", "curr", "serde", "base64"]

[workspace.dependencies.soroban-env-host]
package = "soroban-env-host-zephyr"
#path = "../rs-soroban-env/soroban-env-host"
git = "https://github.com/heytdep/rs-soroban-env"
branch="stellar-main-2"
features = ["testutils", "next"]
